import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import AuthGuard from "./components/Authguard";
import { LoadingProvider, useLoading } from "./components/LoadingProvider";
import LoadingWrapper from "./components/LoadingWrapper";
import { Toaster } from "react-hot-toast"; 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="lemonade">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className=" ">
          <AuthGuard>
            <LoadingProvider>
              <Navbar />
              <LoadingWrapper>
                <Toaster />
                <div className=" pt-20">
                  {children}
                </div>
              </LoadingWrapper>

            </LoadingProvider>

          </AuthGuard>

        </div>


      </body>
    </html>
  );
}
